#Métodos Numéricos UN 2021

Andres Alejandro Bonilla Duarte

*aabonilld@unal.edu.co*

Lab 4. QUANTCONECT. Tutorial 4.

In [ ]:
import numpy as np

In [ ]:
#price_list = [143.73, 145.83, 143.68, 144.02, 143.5, 142.62]
mypricelist = [1.3, 1.3, 1.3, 1.3, 1.3, 1.3]
price_array = np.array(mypricelist)
print(price_array, type(price_array))

[1.3 1.3 1.3 1.3 1.3 1.3] <class 'numpy.ndarray'>


In [ ]:
price_list = [143.73, 145.83, 143.68, 144.02, 143.5, 142.62]
price_array = np.array(price_list)
print(price_array, type(price_array))

[143.73 145.83 143.68 144.02 143.5  142.62] <class 'numpy.ndarray'>


In [ ]:
Ar = np.array([[1,3],[2,4]])
print(Ar, type(Ar))

[[1 3]
 [2 4]] <class 'numpy.ndarray'>


In [ ]:
myarray = np.array([[1,0],[0,1]])
print(myarray)
print(type(myarray))

[[1 0]
 [0 1]]
<class 'numpy.ndarray'>


In [ ]:
print(Ar.shape)

(2, 2)


In [ ]:
print(myarray.shape)

(2, 2)


In [ ]:
print(Ar[0])
print(Ar[1])

[1 3]
[2 4]


In [ ]:
print(myarray[0])
print(myarray[1])

[1 0]
[0 1]


In [ ]:
print('the first column: ', Ar[:,0])
print('the second column: ', Ar[:,1])

the first column:  [1 2]
the second column:  [3 4]


In [ ]:
print('columna 0', myarray[:,0])
print('columna 1', myarray[:,1])

columna 0 [1 0]
columna 1 [0 1]


In [ ]:
print(np.log(price_array))

[ 4.96793654  4.98244156  4.9675886   4.96995218  4.96633504  4.96018375]


In [ ]:
print(np.log(price_array))

[0.26236426 0.26236426 0.26236426 0.26236426 0.26236426 0.26236426]


In [ ]:
print(np.mean(price_array))
print(np.std(price_array))
print(np.sum(price_array))
print(np.max(price_array))

143.89666666666668
0.9673790478515796
863.38
145.83


In [ ]:
print(np.mean(price_array))
print(np.std(price_array))
print(np.sum(price_array))
print(np.max(price_array))

1.3
0.0
7.8
1.3


In [ ]:
import pandas as pd

In [ ]:
price = [143.73, 145.83, 143.68, 144.02, 143.5, 142.62]
s = pd.Series(price)
s

0    143.73
1    145.83
2    143.68
3    144.02
4    143.50
5    142.62
dtype: float64

In [ ]:
price = [1.73, 2.83, 3.68, 4.02, 5.5, 6.62]
s = pd.Series(price)
s

0    1.73
1    2.83
2    3.68
3    4.02
4    5.50
5    6.62
dtype: float64

In [ ]:
s = pd.Series(price,index = ['a','b','c','d','e','f'])
s

a    143.73
b    145.83
c    143.68
d    144.02
e    143.50
f    142.62
dtype: float64

In [ ]:
s = pd.Series(price,index = ['a0','b1','c2','d3','e4','f5'])
s

a0    1.73
b1    2.83
c2    3.68
d3    4.02
e4    5.50
f5    6.62
dtype: float64

In [ ]:
s.index = [6,5,4,3,2,1]
s

6    143.73
5    145.83
4    143.68
3    144.02
2    143.50
1    142.62
dtype: float64

In [ ]:
s.index = ['a','b','c','d','e','f']
s

a    1.73
b    2.83
c    3.68
d    4.02
e    5.50
f    6.62
dtype: float64

In [ ]:
print(s[1:])
print(s[:-2])

5    145.83
4    143.68
3    144.02
2    143.50
1    142.62
dtype: float64
6    143.73
5    145.83
4    143.68
3    144.02
dtype: float64


In [ ]:
print(s[1:])
print(s[:-2])

b    2.83
c    3.68
d    4.02
e    5.50
f    6.62
dtype: float64
a    1.73
b    2.83
c    3.68
d    4.02
dtype: float64


In [ ]:
print(s[4])
s[4] = 0
print(s)

143.68
6    143.73
5    145.83
4      0.00
3    144.02
2    143.50
1    142.62
dtype: float64


In [ ]:
print(s[4])
s[4] = 0
print(s)

5.5
a    1.73
b    2.83
c    3.68
d    4.02
e    0.00
f    6.62
dtype: float64


In [ ]:
s = pd.Series(price, name = 'Apple Price List')
print(s)
print(s.name)

0    143.73
1    145.83
2    143.68
3    144.02
4    143.50
5    142.62
Name: Apple Price List, dtype: float64
Apple Price List


In [ ]:
mys = pd.Series(price, name = 'Example. Apple Price List')
print(mys)
print(mys.name)

0    1.73
1    2.83
2    3.68
3    4.02
4    5.50
5    6.62
Name: Example. Apple Price List, dtype: float64
Example. Apple Price List


In [ ]:
time_index = pd.date_range('2017-01-01',periods = len(s),freq = 'D')
print(time_index)
s.index = time_index
print(s)

DatetimeIndex(['2017-01-01', '2017-01-02', '2017-01-03', '2017-01-04',
               '2017-01-05', '2017-01-06'],
              dtype='datetime64[ns]', freq='D')
2017-01-01    143.73
2017-01-02    145.83
2017-01-03    143.68
2017-01-04    144.02
2017-01-05    143.50
2017-01-06    142.62
Freq: D, Name: Apple Price List, dtype: float64


In [ ]:
time_index = pd.date_range('2017-01-01',periods = len(mys),freq = 'M')
print(time_index)
mys.index = time_index
print(mys)

DatetimeIndex(['2017-01-31', '2017-02-28', '2017-03-31', '2017-04-30',
               '2017-05-31', '2017-06-30'],
              dtype='datetime64[ns]', freq='M')
2017-01-31    1.73
2017-02-28    2.83
2017-03-31    3.68
2017-04-30    4.02
2017-05-31    5.50
2017-06-30    6.62
Freq: M, Name: Example. Apple Price List, dtype: float64


In [ ]:
s.index = [6,5,4,3,2,1]
print(s)
print(s[1])

6    143.73
5    145.83
4    143.68
3    144.02
2    143.50
1    142.62
Name: Apple Price List, dtype: float64
142.62


In [ ]:
mys.index = [6,5,4,3,2,1]
print(mys)
print(mys[1])

6    1.73
5    2.83
4    3.68
3    4.02
2    5.50
1    6.62
Name: Example. Apple Price List, dtype: float64
6.62


In [ ]:
print(s.iloc[1])

145.83


In [ ]:
print(mys.iloc[1])

2.83


In [ ]:
s.index = time_index
print(s['2017-01-03'])

143.68


In [ ]:
mys.index = time_index
print(mys['2017-01-03'])

In [ ]:
print(s['2017-01-02':'2017-01-05'])

Series([], Freq: M, dtype: float64)


In [ ]:
print(mys['2017-01-02':'2017-01-05'])

In [ ]:
print(s[s < np.mean(s)] )
print([(s > np.mean(s)) & (s < np.mean(s) + 1.64*np.std(s))])

6    143.73
4    143.68
2    143.50
1    142.62
Name: Apple Price List, dtype: float64
[6    False
5    False
4    False
3     True
2    False
1    False
Name: Apple Price List, dtype: bool]


In [ ]:
print(mys[mys < np.mean(mys)] )
print([(mys > np.mean(mys)) & (mys < np.mean(mys) + 1.64*np.std(mys))])

6    1.73
5    2.83
4    3.68
3    4.02
Name: Example. Apple Price List, dtype: float64
[6    False
5    False
4    False
3    False
2     True
1     True
Name: Example. Apple Price List, dtype: bool]
