In [3]:
pip install -U fortran-magic

Requirement already up-to-date: fortran-magic in /usr/local/lib/python3.7/dist-packages (0.7)


In [4]:
%reload_ext fortranmagic

/usr/local/lib/python3.7/dist-packages/fortranmagic.py:147: UserWarning: get_ipython_cache_dir has moved to the IPython.paths module since IPython 4.0.
  self._lib_dir = os.path.join(get_ipython_cache_dir(), 'fortran')


In [5]:
%matplotlib inline
%load_ext fortranmagic

import sys; sys.path.append('..')

import pandas as pd
import numpy as np
import matplotlib as mpl
import matplotlib.pyplot as plt
import seaborn as sns

mpl.rc('figure', figsize=(12, 7))

ran_the_first_cell = True

jan2017 = pd.to_datetime(['2017-01-03 00:00:00+00:00',
 '2017-01-04 00:00:00+00:00',
 '2017-01-05 00:00:00+00:00',
 '2017-01-06 00:00:00+00:00',
 '2017-01-09 00:00:00+00:00',
 '2017-01-10 00:00:00+00:00',
 '2017-01-11 00:00:00+00:00',
 '2017-01-12 00:00:00+00:00',
 '2017-01-13 00:00:00+00:00',
 '2017-01-17 00:00:00+00:00',
 '2017-01-18 00:00:00+00:00',
 '2017-01-19 00:00:00+00:00',
 '2017-01-20 00:00:00+00:00',
 '2017-01-23 00:00:00+00:00',
 '2017-01-24 00:00:00+00:00',
 '2017-01-25 00:00:00+00:00',
 '2017-01-26 00:00:00+00:00',
 '2017-01-27 00:00:00+00:00',
 '2017-01-30 00:00:00+00:00',
 '2017-01-31 00:00:00+00:00',
 '2017-02-01 00:00:00+00:00'])
calendar = jan2017.values.astype('datetime64[D]')

event_dates = pd.to_datetime(['2017-01-06 00:00:00+00:00', 
                             '2017-01-07 00:00:00+00:00', 
                             '2017-01-08 00:00:00+00:00']).values.astype('datetime64[D]')
event_values = np.array([10, 15, 20])

The fortranmagic extension is already loaded. To reload it, use:
  %reload_ext fortranmagic


<center>
  <h1>The PyData Toolbox</h1>
  <h3>Scott Sanderson (Twitter: @scottbsanderson, GitHub: ssanderson)</h3>
  <h3><a href="https://github.com/ssanderson/pydata-toolbox">https://github.com/ssanderson/pydata-toolbox</a></h3>
</center>

# About Me:

<img src="images/me.jpg" alt="Drawing" style="width: 300px;"/>

- Senior Engineer at [Quantopian](www.quantopian.com)
- Background in Mathematics and Philosophy
- **Twitter:** [@scottbsanderson](https://twitter.com/scottbsanderson)
- **GitHub:** [ssanderson](github.com/ssanderson)

## Outline

- Built-in Data Structures
- Numpy `array`
- Pandas `Series`/`DataFrame`
- Plotting and "Real-World" Analyses

# Data Structures

> Rule 5. Data dominates. If you've chosen the right data structures and organized things well, the algorithms
will almost always be self-evident. Data structures, not algorithms, are central to programming.

- *Notes on Programming in C*, by Rob Pike.

# Lists

In [6]:
assert ran_the_first_cell, "Oh noes!"

In [7]:
assert ran_the_first_cell,"aabonillad"

In [8]:
l = [1, 'two', 3.0, 4, 5.0, "six"]
l

[1, 'two', 3.0, 4, 5.0, 'six']

In [9]:
lst = [2, 4, 'six', 6.0, 7, "eigth"]
lst

[2, 4, 'six', 6.0, 7, 'eigth']

In [10]:
myList = [6,5,4,3,2,1,0]
myList

[6, 5, 4, 3, 2, 1, 0]

In [11]:
mylist0 = [1, 2, 3, 4, 5]
mylist0

[1, 2, 3, 4, 5]

In [12]:
# Lists can be indexed like C-style arrays.
first = l[0]
second = l[1]
print("first:", first)
print("second:", second)

first: 1
second: two


In [13]:
lst[2:]

['six', 6.0, 7, 'eigth']

In [14]:
# Negative indexing gives elements relative to the end of the list.
last = l[-1]
penultimate = l[-2]
print("last:", last)
print("second to last:", penultimate)

last: six
second to last: 5.0


In [15]:
print('reverse list - negative step')
print(lst[::-1])

reverse list - negative step
['eigth', 7, 6.0, 'six', 4, 2]


In [16]:
# Lists can also be sliced, which makes a copy of elements between 
# start (inclusive) and stop (exclusive)
sublist = l[1:3]
sublist

['two', 3.0]

In [17]:
print('slice list')
lst[3:5]

slice list


[6.0, 7]

In [18]:
# l[:N] is equivalent to l[0:N].
first_three = l[:3]
first_three

[1, 'two', 3.0]

In [19]:
print(len(lst))
n = input('intervalo')
lst[:int(n)]

6
intervalo3


[2, 4, 'six']

In [20]:
# l[3:] is equivalent to l[3:len(l)].
after_three = l[3:]
after_three

[4, 5.0, 'six']

In [21]:
print(len(lst))
n = input('intervalo')
lst[int(n):]

6
intervalo6


[]

In [22]:
# There's also a third parameter, "step", which gets every Nth element.
l = ['a', 'b', 'c', 'd', 'e', 'f', 'g','h']
l[1:7:2]

['b', 'd', 'f']

In [23]:
list0 = list(range(0,12))
list0[2:10:3]

[2, 5, 8]

In [24]:
# This is a cute way to reverse a list.
l[::-1]

['h', 'g', 'f', 'e', 'd', 'c', 'b', 'a']

In [25]:
list0[::-1]

[11, 10, 9, 8, 7, 6, 5, 4, 3, 2, 1, 0]

In [26]:
# Lists can be grown efficiently (in O(1) amortized time).
l = [1, 2, 3, 4, 5]
print("Before:", l)
l.append('six')
print("After:", l)

Before: [1, 2, 3, 4, 5]
After: [1, 2, 3, 4, 5, 'six']


In [27]:
list0.append(100)
list0

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 100]

In [28]:
# Comprehensions let us perform elementwise computations.
l = [1, 2, 3, 4, 5]
[x * 2 for x in l]

[2, 4, 6, 8, 10]

In [29]:
l = [1, 2, 3, 4, 5]
[2 ** x for x in l]

[2, 4, 8, 16, 32]

## Review: Python Lists

- Zero-indexed sequence of arbitrary Python values.
- Slicing syntax: `l[start:stop:step]` copies elements at regular intervals from `start` to `stop`.
- Efficient (`O(1)`) appends and removes from end.
- Comprehension syntax: `[f(x) for x in l if cond(x)]`.

# Dictionaries

In [30]:
# Dictionaries are key-value mappings.
philosophers = {'David': 'Hume', 'Immanuel': 'Kant', 'Bertrand': 'Russell'}
philosophers

{'Bertrand': 'Russell', 'David': 'Hume', 'Immanuel': 'Kant'}

In [31]:
mydict = {'a':3, 'b':4, 'c':5}
mydict

{'a': 3, 'b': 4, 'c': 5}

In [32]:
# Like lists, dictionaries are size-mutable.
philosophers['Ludwig'] = 'Wittgenstein'
philosophers

{'Bertrand': 'Russell',
 'David': 'Hume',
 'Immanuel': 'Kant',
 'Ludwig': 'Wittgenstein'}

In [33]:
mydict['new'] = 777
mydict

{'a': 3, 'b': 4, 'c': 5, 'new': 777}

In [34]:
del philosophers['David']
philosophers

{'Bertrand': 'Russell', 'Immanuel': 'Kant', 'Ludwig': 'Wittgenstein'}

In [35]:
# No slicing.
philosophers['Bertrand':'Immanuel']

TypeError: ignored

In [36]:
mydict['a':'new']

TypeError: ignored

## Review: Python Dictionaries

- Unordered key-value mapping from (almost) arbitrary keys to arbitrary values.
- Efficient (`O(1)`) lookup, insertion, and deletion.
- No slicing (would require a notion of order).

<center><img src="images/pacino.gif" alt="Drawing" style="width: 100%;"/></center>


In [37]:
# Suppose we have some matrices...
a = [[1, 2, 3],
     [2, 3, 4],
     [5, 6, 7],
     [1, 1, 1]]

b = [[1, 2, 3, 4],
     [2, 3, 4, 5]]

In [38]:
m0 = [[0, 1, 2],
      [1, 1, 1],
      [2, 1, 1]
      ]
m1 = [[1, 2],
      [1, 0],
      [1, 1]]

In [39]:
def matmul(A, B):
    """Multiply matrix A by matrix B."""
    rows_out = len(A)
    cols_out = len(B[0])
    out = [[0 for col in range(cols_out)] for row in range(rows_out)]
    
    for i in range(rows_out):
        for j in range(cols_out):
            for k in range(len(B)):
                out[i][j] += A[i][k] * B[k][j]
    return out

<center><img src="images/gross.gif" alt="Drawing" style="width: 50%;"/></center>


In [40]:
%%time

matmul(a, b)

CPU times: user 44 µs, sys: 8 µs, total: 52 µs
Wall time: 56.7 µs


[[5, 8, 11, 14], [8, 13, 18, 23], [17, 28, 39, 50], [3, 5, 7, 9]]

In [41]:

%%time

matmul(m0, m1)

CPU times: user 25 µs, sys: 5 µs, total: 30 µs
Wall time: 33.1 µs


[[3, 2], [3, 3], [4, 5]]

In [42]:
import random
def random_matrix(m, n):
    out = []
    for row in range(m):
        out.append([random.random() for _ in range(n)])
    return out

randm = random_matrix(2, 3)
randm

[[0.5444773850995079, 0.40450430041059593, 0.008795149090570775],
 [0.5648593328813847, 0.7658940634745056, 0.9514307996519535]]

In [43]:
mr = random_matrix(3, 3)
mr

[[0.20572700939176258, 0.10438960381543239, 0.6857645867116903],
 [0.5375941353895017, 0.4269276264384374, 0.6991543629417071],
 [0.9880871087196675, 0.6584086365318954, 0.5183791765256737]]

In [44]:
%%time
randa = random_matrix(600, 100)
randb = random_matrix(100, 600)
x = matmul(randa, randb)

CPU times: user 10.5 s, sys: 50.8 ms, total: 10.6 s
Wall time: 10.6 s


In [45]:
# Maybe that's not that bad?  Let's try a simpler case.
def python_dot_product(xs, ys):
    return sum(x * y for x, y in zip(xs, ys))

In [46]:
%%fortran
subroutine fortran_dot_product(xs, ys, result)
    double precision, intent(in) :: xs(:)
    double precision, intent(in) :: ys(:)
    double precision, intent(out) :: result
    
    result = sum(xs * ys)
end

In [47]:
list_data = [float(i) for i in range(100000)]
array_data = np.array(list_data)

In [48]:
%%time
python_dot_product(list_data, list_data)

CPU times: user 12.1 ms, sys: 4 µs, total: 12.1 ms
Wall time: 12.1 ms


333328333350000.0

In [49]:
%%time
fortran_dot_product(array_data, array_data)

CPU times: user 204 µs, sys: 0 ns, total: 204 µs
Wall time: 215 µs


333328333350000.0

<center><img src="images/sloth.gif" alt="Drawing" style="width: 1080px;"/></center>


## Why is the Python Version so Much Slower?

In [50]:
# Dynamic typing.
def mul_elemwise(xs, ys):
    return [x * y for x, y in zip(xs, ys)]

mul_elemwise([1, 2, 3, 4], [1, 2 + 0j, 3.0, 'four'])
#[type(x) for x in _]

[1, (4+0j), 9.0, 'fourfourfourfour']

In [51]:
def mul_elemwise(xs, ys):
    return [x * y for x, y in zip(xs, ys)]

mul_elemwise([1, 2, 5, 7], [2, 1 + 0j, 3.0, 'four'])
#[type(x) for x in _]

[2, (2+0j), 15.0, 'fourfourfourfourfourfourfour']

In [52]:
# Interpretation overhead.
source_code = 'a + b * c'
bytecode = compile(source_code, '', 'eval')
import dis; dis.dis(bytecode)

  1           0 LOAD_NAME                0 (a)
              2 LOAD_NAME                1 (b)
              4 LOAD_NAME                2 (c)
              6 BINARY_MULTIPLY
              8 BINARY_ADD
             10 RETURN_VALUE


In [53]:
# Interpretation overhead.
source_code = 'a + b * c'
bytecode = compile(source_code, '', 'eval')
import dis; dis.dis(bytecode)

  1           0 LOAD_NAME                0 (a)
              2 LOAD_NAME                1 (b)
              4 LOAD_NAME                2 (c)
              6 BINARY_MULTIPLY
              8 BINARY_ADD
             10 RETURN_VALUE


## Why is the Python Version so Slow?
- Dynamic typing means that every single operation requires dispatching on the input type.
- Having an interpreter means that every instruction is fetched and dispatched at runtime.
- Other overheads:
  - Arbitrary-size integers.
  - Reference-counted garbage collection.

> This is the paradox that we have to work with when we're doing scientific or numerically-intensive Python. What makes Python fast for development -- this high-level, interpreted, and dynamically-typed aspect of the language -- is exactly what makes it slow for code execution.

- Jake VanderPlas, [*Losing Your Loops: Fast Numerical Computing with NumPy*](https://www.youtube.com/watch?v=EEUXKG97YRw)

# What Do We Do?

<center><img src="images/runaway.gif" alt="Drawing" style="width: 50%;"/></center>

<center><img src="images/thisisfine.gif" alt="Drawing" style="width: 1080px;"/></center>

- Python is slow for numerical computation because it performs dynamic dispatch on every operation we perform...

- ...but often, we just want to do the same thing over and over in a loop!

- If we don't need Python's dynamicism, we don't want to pay (much) for it.

- **Idea:** Dispatch **once per operation** instead of **once per element**.

In [54]:
import numpy as np

data = np.array([1, 2, 3, 4])
data

array([1, 2, 3, 4])

In [55]:
mydata = np.array([1, 2, 3, 4])
mydata

array([1, 2, 3, 4])

In [56]:
data + data

array([2, 4, 6, 8])

In [57]:
data + mydata

array([2, 4, 6, 8])

In [58]:
%%time
# Naive dot product
(array_data * array_data).sum()

CPU times: user 95 µs, sys: 1.01 ms, total: 1.1 ms
Wall time: 1.2 ms


333328333350000.0

In [59]:
%%time
(mydata * mydata).sum()

CPU times: user 73 µs, sys: 4 µs, total: 77 µs
Wall time: 84.2 µs


30

In [60]:
%%time
# Built-in dot product.
data.dot(data)

CPU times: user 33 µs, sys: 2 µs, total: 35 µs
Wall time: 39.6 µs


30

In [61]:

%%time
print(mydata.dot(mydata))
print(mydata)

30
[1 2 3 4]
CPU times: user 713 µs, sys: 984 µs, total: 1.7 ms
Wall time: 1.88 ms


In [62]:
%%time
print(mydata.dot(mydata))

30
CPU times: user 885 µs, sys: 0 ns, total: 885 µs
Wall time: 894 µs


In [63]:
%%time
fortran_dot_product(array_data, array_data)

CPU times: user 216 µs, sys: 0 ns, total: 216 µs
Wall time: 456 µs


333328333350000.0

In [65]:
# Numpy won't allow us to write a string into an int array.
data[0] = "foo"

ValueError: ignored

In [66]:
# We also can't grow an array once it's created.
data.append(3)

AttributeError: ignored

In [67]:
mydata.append(1341)

AttributeError: ignored

In [68]:
# We **can** reshape an array though.
two_by_two = data.reshape(2, 2)
two_by_two

array([[1, 2],
       [3, 4]])

In [69]:
txt = mydata.reshape(2, 2)
txt

array([[1, 2],
       [3, 4]])

Numpy arrays are:

- Fixed-type

- Size-immutable

- Multi-dimensional

- Fast\*

\* If you use them correctly.

# What's in an Array?

In [70]:
arr = np.array([1, 2, 3, 4, 5, 6], dtype='int16').reshape(2, 3)
print("Array:\n", arr, sep='')
print("===========")
print("DType:", arr.dtype)
print("Shape:", arr.shape)
print("Strides:", arr.strides)
print("Data:", arr.data.tobytes())

Array:
[[1 2 3]
 [4 5 6]]
DType: int16
Shape: (2, 3)
Strides: (6, 2)
Data: b'\x01\x00\x02\x00\x03\x00\x04\x00\x05\x00\x06\x00'


In [71]:
arr = np.array([1, 2, 3, 4, 5, 6, 0, 0], dtype='int16').reshape(2, 4)
print("Array:\n", arr, sep='')
print("===========")
print("DType:", arr.dtype)
print("Shape:", arr.shape)
print("Strides:", arr.strides)
print("Data:", arr.data.tobytes())

Array:
[[1 2 3 4]
 [5 6 0 0]]
DType: int16
Shape: (2, 4)
Strides: (8, 2)
Data: b'\x01\x00\x02\x00\x03\x00\x04\x00\x05\x00\x06\x00\x00\x00\x00\x00'


# Core Operations

- Vectorized **ufuncs** for elementwise operations.
- Fancy indexing and masking for selection and filtering.
- Aggregations across axes.
- Broadcasting

# UFuncs

UFuncs (universal functions) are functions that operate elementwise on one or more arrays.

In [72]:
data = np.arange(15).reshape(3, 5)
data

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [73]:
mydata = np.arange(64).reshape(4, 16)
mydata

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47],
       [48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63]])

In [74]:
# Binary operators.
data * data

array([[  0,   1,   4,   9,  16],
       [ 25,  36,  49,  64,  81],
       [100, 121, 144, 169, 196]])

In [75]:
mydata * mydata

array([[   0,    1,    4,    9,   16,   25,   36,   49,   64,   81,  100,
         121,  144,  169,  196,  225],
       [ 256,  289,  324,  361,  400,  441,  484,  529,  576,  625,  676,
         729,  784,  841,  900,  961],
       [1024, 1089, 1156, 1225, 1296, 1369, 1444, 1521, 1600, 1681, 1764,
        1849, 1936, 2025, 2116, 2209],
       [2304, 2401, 2500, 2601, 2704, 2809, 2916, 3025, 3136, 3249, 3364,
        3481, 3600, 3721, 3844, 3969]])

In [76]:
# Unary functions.
np.sqrt(data)

array([[0.        , 1.        , 1.41421356, 1.73205081, 2.        ],
       [2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ],
       [3.16227766, 3.31662479, 3.46410162, 3.60555128, 3.74165739]])

In [77]:

np.sqrt(mydata)

array([[0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
        2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
        3.16227766, 3.31662479, 3.46410162, 3.60555128, 3.74165739,
        3.87298335],
       [4.        , 4.12310563, 4.24264069, 4.35889894, 4.47213595,
        4.58257569, 4.69041576, 4.79583152, 4.89897949, 5.        ,
        5.09901951, 5.19615242, 5.29150262, 5.38516481, 5.47722558,
        5.56776436],
       [5.65685425, 5.74456265, 5.83095189, 5.91607978, 6.        ,
        6.08276253, 6.164414  , 6.244998  , 6.32455532, 6.40312424,
        6.4807407 , 6.55743852, 6.63324958, 6.70820393, 6.78232998,
        6.8556546 ],
       [6.92820323, 7.        , 7.07106781, 7.14142843, 7.21110255,
        7.28010989, 7.34846923, 7.41619849, 7.48331477, 7.54983444,
        7.61577311, 7.68114575, 7.74596669, 7.81024968, 7.87400787,
        7.93725393]])

In [78]:
# Comparison operations
(data % 3) == 0

array([[ True, False, False,  True, False],
       [False,  True, False, False,  True],
       [False, False,  True, False, False]])

In [79]:
mydata % 2 == 0

array([[ True, False,  True, False,  True, False,  True, False,  True,
        False,  True, False,  True, False,  True, False],
       [ True, False,  True, False,  True, False,  True, False,  True,
        False,  True, False,  True, False,  True, False],
       [ True, False,  True, False,  True, False,  True, False,  True,
        False,  True, False,  True, False,  True, False],
       [ True, False,  True, False,  True, False,  True, False,  True,
        False,  True, False,  True, False,  True, False]])

In [80]:
# Boolean combinators.
((data % 2) == 0) & ((data % 3) == 0)

array([[ True, False, False, False, False],
       [False,  True, False, False, False],
       [False, False,  True, False, False]])

In [82]:
((mydata % 5) == 0) & ((mydata % 2) == 0)

array([[ True, False, False, False, False, False, False, False, False,
        False,  True, False, False, False, False, False],
       [False, False, False, False,  True, False, False, False, False,
        False, False, False, False, False,  True, False],
       [False, False, False, False, False, False, False, False,  True,
        False, False, False, False, False, False, False],
       [False, False,  True, False, False, False, False, False, False,
        False, False, False,  True, False, False, False]])

In [83]:
# as of python 3.5, @ is matrix-multiply
data @ data.T

array([[ 30,  80, 130],
       [ 80, 255, 430],
       [130, 430, 730]])

In [84]:
mydata @ mydata.T

array([[ 1240,  3160,  5080,  7000],
       [ 3160,  9176, 15192, 21208],
       [ 5080, 15192, 25304, 35416],
       [ 7000, 21208, 35416, 49624]])

# UFuncs Review

- UFuncs provide efficient elementwise operations applied across one or more arrays.
- Arithmetic Operators (`+`, `*`, `/`)
- Comparisons (`==`, `>`, `!=`)
- Boolean Operators (`&`, `|`, `^`)
- Trigonometric Functions (`sin`, `cos`)
- Transcendental Functions (`exp`, `log`)

# Selections

We often want to perform an operation on just a subset of our data.

In [85]:
sines = np.sin(np.linspace(0, 3.14, 10))
cosines = np.cos(np.linspace(0, 3.14, 10))
sines

array([0.        , 0.34185385, 0.64251645, 0.86575984, 0.98468459,
       0.98496101, 0.8665558 , 0.64373604, 0.34335012, 0.00159265])

In [86]:
mysines = np.sin(np.linspace(0, 3.14, 10))
mycosines = np.cos(np.linspace(0, 3.14, 10))
mysines

array([0.        , 0.34185385, 0.64251645, 0.86575984, 0.98468459,
       0.98496101, 0.8665558 , 0.64373604, 0.34335012, 0.00159265])

In [87]:
# Slicing works with the same semantics as Python lists.
sines[0]

0.0

In [88]:
print(mysines[1] , mycosines[1])

0.34185384854620343 0.9397531304731841


In [89]:
sines[:3]  # First three elements  

array([0.        , 0.34185385, 0.64251645])

In [90]:
mysines[:4]

array([0.        , 0.34185385, 0.64251645, 0.86575984])

In [91]:
sines[5:]  # Elements from 5 on.

array([0.98496101, 0.8665558 , 0.64373604, 0.34335012, 0.00159265])

In [92]:
sines[4:]

array([0.98468459, 0.98496101, 0.8665558 , 0.64373604, 0.34335012,
       0.00159265])

In [93]:
sines[::2]  # Every other element.

array([0.        , 0.64251645, 0.98468459, 0.8665558 , 0.34335012])

In [94]:
mysines[::-1]

array([0.00159265, 0.34335012, 0.64373604, 0.8665558 , 0.98496101,
       0.98468459, 0.86575984, 0.64251645, 0.34185385, 0.        ])

In [95]:
# More interesting: we can index with boolean arrays to filter by a predicate.
print("sines:\n", sines)
print("sines > 0.5:\n", sines > 0.5)
print("sines[sines > 0.5]:\n", sines[sines > 0.5])

sines:
 [0.         0.34185385 0.64251645 0.86575984 0.98468459 0.98496101
 0.8665558  0.64373604 0.34335012 0.00159265]
sines > 0.5:
 [False False  True  True  True  True  True  True False False]
sines[sines > 0.5]:
 [0.64251645 0.86575984 0.98468459 0.98496101 0.8665558  0.64373604]


In [96]:
print(mysines > 0.5)
print(mycosines > 0.5)

[False False  True  True  True  True  True  True False False]
[ True  True  True  True False False False False False False]


In [97]:
# We index with lists/arrays of integers to select values at those indices.
print(sines)
sines[[0, 4, 7]]

[0.         0.34185385 0.64251645 0.86575984 0.98468459 0.98496101
 0.8665558  0.64373604 0.34335012 0.00159265]


array([0.        , 0.98468459, 0.64373604])

In [98]:
print(sines[[0,1,2]])

[0.         0.34185385 0.64251645]


In [99]:
# Index arrays are often used for sorting one or more arrays.
unsorted_data = np.array([1, 3, 2, 12, -1, 5, 2])

In [100]:
myunsorteddata = np.array([1,6,2,5,7,42,4])

In [101]:
sort_indices = np.argsort(unsorted_data)
sort_indices

array([4, 0, 2, 6, 1, 5, 3])

In [102]:
mysortdata = np.argsort(myunsorteddata)
mysortdata

array([0, 2, 6, 3, 1, 4, 5])

In [103]:
unsorted_data[sort_indices]

array([-1,  1,  2,  2,  3,  5, 12])

In [104]:
myunsorteddata[mysortdata]

array([ 1,  2,  4,  5,  6,  7, 42])

In [105]:
market_caps = np.array([12, 6, 10, 5, 6])  # Presumably in dollars?
assets = np.array(['A', 'B', 'C', 'D', 'E'])

In [106]:
mycaps = np.array([13, 7, 11, 6, 7])
myassets = np.array(['A', 'B', 'C', 'D', 'E'])

In [107]:
# Sort assets by market cap by using the permutation that would sort market caps on ``assets``.
sort_by_mcap = np.argsort(market_caps)
assets[sort_by_mcap]

array(['D', 'B', 'E', 'C', 'A'], dtype='<U1')

In [108]:
sortbymcaps = np.argsort(mycaps)
myassets[sortbymcaps]

array(['D', 'B', 'E', 'C', 'A'], dtype='<U1')

In [109]:
# Indexers are also useful for aligning data.
print("Dates:\n", repr(event_dates))
print("Values:\n", repr(event_values))
print("Calendar:\n", repr(calendar))

Dates:
 array(['2017-01-06', '2017-01-07', '2017-01-08'], dtype='datetime64[D]')
Values:
 array([10, 15, 20])
Calendar:
 array(['2017-01-03', '2017-01-04', '2017-01-05', '2017-01-06',
       '2017-01-09', '2017-01-10', '2017-01-11', '2017-01-12',
       '2017-01-13', '2017-01-17', '2017-01-18', '2017-01-19',
       '2017-01-20', '2017-01-23', '2017-01-24', '2017-01-25',
       '2017-01-26', '2017-01-27', '2017-01-30', '2017-01-31',
       '2017-02-01'], dtype='datetime64[D]')


In [110]:
print("Dates:\n", repr(event_dates))
print("Values:\n", repr(event_values))
print("Calendar:\n", repr(calendar))

Dates:
 array(['2017-01-06', '2017-01-07', '2017-01-08'], dtype='datetime64[D]')
Values:
 array([10, 15, 20])
Calendar:
 array(['2017-01-03', '2017-01-04', '2017-01-05', '2017-01-06',
       '2017-01-09', '2017-01-10', '2017-01-11', '2017-01-12',
       '2017-01-13', '2017-01-17', '2017-01-18', '2017-01-19',
       '2017-01-20', '2017-01-23', '2017-01-24', '2017-01-25',
       '2017-01-26', '2017-01-27', '2017-01-30', '2017-01-31',
       '2017-02-01'], dtype='datetime64[D]')


In [111]:
print("Raw Dates:", event_dates)
print("Indices:", calendar.searchsorted(event_dates))
print("Forward-Filled Dates:", calendar[calendar.searchsorted(event_dates)])

Raw Dates: ['2017-01-06' '2017-01-07' '2017-01-08']
Indices: [3 4 4]
Forward-Filled Dates: ['2017-01-06' '2017-01-09' '2017-01-09']


In [112]:
print("Raw Dates:", event_dates)
print("Indices:", calendar.searchsorted(event_dates))
print("Forward-Filled Dates:", calendar[calendar.searchsorted(event_dates)])

Raw Dates: ['2017-01-06' '2017-01-07' '2017-01-08']
Indices: [3 4 4]
Forward-Filled Dates: ['2017-01-06' '2017-01-09' '2017-01-09']


On multi-dimensional arrays, we can slice along each axis independently.

In [113]:
data = np.arange(25).reshape(5, 5)
data

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [114]:
mydata = np.arange(16).reshape(4, 4)
mydata

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [115]:
mydata[:2, :2]

array([[0, 1],
       [4, 5]])

In [116]:
data[:2, :2]  # First two rows and first two columns.

array([[0, 1],
       [5, 6]])

In [117]:
data[:2, [0, -1]]  # First two rows, first and last columns.

array([[0, 4],
       [5, 9]])

In [118]:
mydata[:2, [0, -1]]

array([[0, 3],
       [4, 7]])

In [119]:
data[(data[:, 0] % 2) == 0]  # Rows where the first column is divisible by two.

array([[ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14],
       [20, 21, 22, 23, 24]])

In [120]:
mydata[(mydata[:, 0] % 2) == 0]

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

# Selections Review

- Indexing with an integer removes a dimension.
- Slicing operations work on Numpy arrays the same way they do on lists.
- Indexing with a boolean array filters to True locations.
- Indexing with an integer array selects indices along an axis.
- Multidimensional arrays can apply selections independently along different axes.

## Reductions

Functions that reduce an array to a scalar.

$Var(X) = \frac{1}{N}\sqrt{\sum_{i=1}^N (x_i - \bar{x})^2}$

In [121]:
def variance(x):
    return ((x - x.mean()) ** 2).sum() / len(x)

In [122]:
variance(np.random.standard_normal(1000))

1.0385932702098235

In [123]:
variance(np.random.standard_normal(100))

0.813559328522928

- `sum()` and `mean()` are both **reductions**.

- In the simplest case, we use these to reduce an entire array into a single value...

In [124]:
data = np.arange(30)
data.mean()

14.5

In [125]:
mydata = np.arange(100)
mydata.mean()

49.5

- ...but we can do more interesting things with multi-dimensional arrays.

In [126]:
data = np.arange(30).reshape(3, 10)
data

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [127]:
mydata = np.arange(40).reshape(4, 10)
mydata

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39]])

In [128]:
data.mean()

14.5

In [129]:
mydata.mean()

19.5

In [130]:
data.mean(axis=0)

array([10., 11., 12., 13., 14., 15., 16., 17., 18., 19.])

In [131]:
mydata.mean(axis=0)

array([15., 16., 17., 18., 19., 20., 21., 22., 23., 24.])

In [132]:
data.mean(axis=1)

array([ 4.5, 14.5, 24.5])

In [133]:
mydata.mean(axis=1)

array([ 4.5, 14.5, 24.5, 34.5])

## Reductions Review

- Reductions allow us to perform efficient aggregations over arrays.
- We can do aggregations over a single axis to collapse a single dimension.
- Many built-in reductions (`mean`, `sum`, `min`, `max`, `median`, ...).

# Broadcasting

In [134]:
row = np.array([1, 2, 3, 4])
column = np.array([[1], [2], [3]])
print("Row:\n", row, sep='')
print("Column:\n", column, sep='')

Row:
[1 2 3 4]
Column:
[[1]
 [2]
 [3]]


In [135]:
myrow = np.array([1, 2, 3, 4, 5])
mycolumn = np.array([[1], [2], [3], [4]])
print("Row:\n", myrow, sep='')
print("Column:\n", mycolumn, sep='')

Row:
[1 2 3 4 5]
Column:
[[1]
 [2]
 [3]
 [4]]


In [136]:
row + column

array([[2, 3, 4, 5],
       [3, 4, 5, 6],
       [4, 5, 6, 7]])

In [137]:
myrow + mycolumn

array([[2, 3, 4, 5, 6],
       [3, 4, 5, 6, 7],
       [4, 5, 6, 7, 8],
       [5, 6, 7, 8, 9]])

<center><img src="images/broadcasting.png" alt="Drawing" style="width: 60%;"/></center>

<h5>Source: http://www.scipy-lectures.org/_images/numpy_broadcasting.png</h5>

In [138]:
# Broadcasting is particularly useful in conjunction with reductions.
print("Data:\n", data, sep='')
print("Mean:\n", data.mean(axis=0), sep='')
print("Data - Mean:\n", data - data.mean(axis=0), sep='')

Data:
[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]]
Mean:
[10. 11. 12. 13. 14. 15. 16. 17. 18. 19.]
Data - Mean:
[[-10. -10. -10. -10. -10. -10. -10. -10. -10. -10.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.]
 [ 10.  10.  10.  10.  10.  10.  10.  10.  10.  10.]]


In [139]:
mydata = myrow + mycolumn
print('my data: \n', mydata, sep='')
print('my mean; \n', mydata.mean(axis=0), sep='')
print('data - mean: \n', mydata - mydata.mean(axis=0), sep='')

my data: 
[[2 3 4 5 6]
 [3 4 5 6 7]
 [4 5 6 7 8]
 [5 6 7 8 9]]
my mean; 
[3.5 4.5 5.5 6.5 7.5]
data - mean: 
[[-1.5 -1.5 -1.5 -1.5 -1.5]
 [-0.5 -0.5 -0.5 -0.5 -0.5]
 [ 0.5  0.5  0.5  0.5  0.5]
 [ 1.5  1.5  1.5  1.5  1.5]]


# Broadcasting Review

- Numpy operations can work on arrays of different dimensions as long as the arrays' shapes are still "compatible".
- Broadcasting works by "tiling" the smaller array along the missing dimension.
- The result of a broadcasted operation is always at least as large in each dimension as the largest array in that dimension.

# Numpy Review

- Numerical algorithms are slow in pure Python because the overhead dynamic dispatch dominates our runtime.

- Numpy solves this problem by:
  1. Imposing additional restrictions on the contents of arrays.
  2. Moving the inner loops of our algorithms into compiled C code.

- Using Numpy effectively often requires reworking an algorithms to use vectorized operations instead of for-loops, but the resulting operations are usually simpler, clearer, and faster than the pure Python equivalent.

<center><img src="images/unicorn.jpg" alt="Drawing" style="width: 75%;"/></center>

Numpy is great for many things, but...

- Sometimes our data is equipped with a natural set of **labels**:
  - Dates/Times
  - Stock Tickers
  - Field Names (e.g. Open/High/Low/Close)

- Sometimes we have **more than one type of data** that we want to keep grouped together.
  - Tables with a mix of real-valued and categorical data.

- Sometimes we have **missing** data, which we need to ignore, fill, or otherwise work around.

<center><img src="images/panda-wrangling.gif" alt="Drawing" style="width: 75%;"/></center>

<center><img src="images/pandas_logo.png" alt="Drawing" style="width: 75%;"/></center>


Pandas extends Numpy with more complex data structures:

- `Series`: 1-dimensional, homogenously-typed, labelled array.
- `DataFrame`: 2-dimensional, semi-homogenous, labelled table.

Pandas also provides many utilities for: 
- Input/Output
- Data Cleaning
- Rolling Algorithms
- Plotting

# Selection in Pandas

In [140]:
import pandas as pd

In [141]:
s = pd.Series(index=['a', 'b', 'c', 'd', 'e'], data=[1, 2, 3, 4, 5])
s

a    1
b    2
c    3
d    4
e    5
dtype: int64

In [142]:
s0 = pd.Series(index=['a', 'b', 'c', 'd', 'e', 'f', 'g'], data=[1, 2, 3, 4, 5, 6, 7])
s0

a    1
b    2
c    3
d    4
e    5
f    6
g    7
dtype: int64

In [143]:
# There are two pieces to a Series: the index and the values.
print("The index is:", s.index)
print("The values are:", s.values)

The index is: Index(['a', 'b', 'c', 'd', 'e'], dtype='object')
The values are: [1 2 3 4 5]


In [144]:
print('index', s0.index)
print('values', s0.values)

index Index(['a', 'b', 'c', 'd', 'e', 'f', 'g'], dtype='object')
values [1 2 3 4 5 6 7]


In [145]:
# We can look up values out of a Series by position...
s.iloc[0]

1

In [146]:
s0.iloc[3]

4

In [147]:
s0.iloc[0]

1

In [148]:
# ... or by label.
s.loc['a']

1

In [149]:
s0.loc['b']

2

In [150]:
# Slicing works as expected...
s.iloc[:2]

a    1
b    2
dtype: int64

In [151]:
s0.iloc[:4]

a    1
b    2
c    3
d    4
dtype: int64

In [152]:
# ...but it works with labels too!
s.loc[:'c']

a    1
b    2
c    3
dtype: int64

In [153]:
s.loc['c':'g']

c    3
d    4
e    5
dtype: int64

In [154]:
# Fancy indexing works the same as in numpy.
s.iloc[[0, -1]]

a    1
e    5
dtype: int64

In [155]:
s0.iloc[[0, -4]]

a    1
d    4
dtype: int64

In [156]:
# As does boolean masking.
s.loc[s > 2]

c    3
d    4
e    5
dtype: int64

In [157]:
s0.loc[s0 > 4]

e    5
f    6
g    7
dtype: int64

In [158]:
# Element-wise operations are aligned by index.
other_s = pd.Series({'a': 10.0, 'c': 20.0, 'd': 30.0, 'z': 40.0})
other_s

a    10.0
c    20.0
d    30.0
z    40.0
dtype: float64

In [159]:
s1 = pd.Series({'a': 11.0, 'c': 22.0, 'd': 33.0, 'z': 44.0})
s1

a    11.0
c    22.0
d    33.0
z    44.0
dtype: float64

In [160]:
s0 + s1

a    12.0
b     NaN
c    25.0
d    37.0
e     NaN
f     NaN
g     NaN
z     NaN
dtype: float64

In [161]:
s + other_s

a    11.0
b     NaN
c    23.0
d    34.0
e     NaN
z     NaN
dtype: float64

In [162]:
# We can fill in missing values with fillna().
(s + other_s).fillna(0.0)

a    11.0
b     0.0
c    23.0
d    34.0
e     0.0
z     0.0
dtype: float64

In [163]:
(s0 + s1).fillna(0.0)

a    12.0
b     0.0
c    25.0
d    37.0
e     0.0
f     0.0
g     0.0
z     0.0
dtype: float64

In [ ]:
# Most real datasets are read in from an external file format.
aapl = pd.read_csv('AAPL.csv', parse_dates=['Date'], index_col='Date')
aapl.head()

In [ ]:
myaapl = pd.read_csv('california_housing_train.cvs', parse_dates=['Date'], index_col='Date')
myaapl.head()

In [ ]:
# Slicing generalizes to two dimensions as you'd expect:
aapl.iloc[:2, :2]

In [ ]:
aapl.loc[pd.Timestamp('2010-02-01'):pd.Timestamp('2010-02-04'), ['Close', 'Volume']]

# Rolling Operations

<center><img src="images/rolling.gif" alt="Drawing" style="width: 75%;"/></center>

In [ ]:
aapl.rolling(5)[['Close', 'Adj Close']].mean().plot();

In [ ]:
# Drop `Volume`, since it's way bigger than everything else.
aapl.drop('Volume', axis=1).resample('2W').max().plot();

In [ ]:
# 30-day rolling exponentially-weighted stddev of returns.
aapl['Close'].pct_change().ewm(span=30).std().plot();

# "Real World" Data

In [ ]:
from demos.avocados import read_avocadata

avocados = read_avocadata('2014', '2016')
avocados.head()

In [ ]:
# Unlike numpy arrays, pandas DataFrames can have a different dtype for each column.
avocados.dtypes

In [ ]:
# What's the regional average price of a HASS avocado every day?
hass = avocados[avocados.Variety == 'HASS']
hass.groupby(['Date', 'Region'])['Weighted Avg Price'].mean().unstack().ffill().plot();

In [ ]:
def _organic_spread(group):

    if len(group.columns) != 2:
        return pd.Series(index=group.index, data=0.0)
    
    is_organic = group.columns.get_level_values('Organic').values.astype(bool)
    organics = group.loc[:, is_organic].squeeze()
    non_organics = group.loc[:, ~is_organic].squeeze()
    diff = organics - non_organics
    return diff

def organic_spread_by_region(df):
    """What's the difference between the price of an organic 
    and non-organic avocado within each region?
    """
    return (
        df
        .set_index(['Date', 'Region', 'Organic'])
         ['Weighted Avg Price']
        .unstack(level=['Region', 'Organic'])
        .ffill()
        .groupby(level='Region', axis=1)
        .apply(_organic_spread)
    )

In [ ]:
organic_spread_by_region(hass).plot();
plt.gca().set_title("Daily Regional Organic Spread");
plt.legend(bbox_to_anchor=(1, 1));

In [ ]:
spread_correlation = organic_spread_by_region(hass).corr()
spread_correlation

In [ ]:
import seaborn as sns
grid = sns.clustermap(spread_correlation, annot=True)
fig = grid.fig
axes = fig.axes
ax = axes[2]
ax.set_xticklabels(ax.get_xticklabels(), rotation=45);

# Pandas Review

- Pandas extends numpy with more complex datastructures and algorithms.
- If you understand numpy, you understand 90% of pandas.
- `groupby`, `set_index`, and `unstack` are powerful tools for working with categorical data.
- Avocado prices are surprisingly interesting :)

# Thanks!